#注意===需要配置所有todo开头的内容===
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://todo数据库地址/lovepig?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: todo数据库访问账户
    password: todo数据库访问密码
  redis:
    host: todo redis服务器地址
    port: todo redis端口
    password: todo redis密码   # 密码（默认为空）
    timeout: 5000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
wx:
  miniapp:
    configs:
      - appid: todo微信小程序appid
        secret: todo微信小程序secret
        msgDataFormat: JSON