#注意===需要配置所有todo开头的内容===
server:
  port: 5210

love:
  static-url: todo静态资源访问地址如https://lmg.jj20.com # 基础路径
  imageType: jpg,jpge,gif,png,bmp
  videoType: webm,mp4,m3u8,3gp
  defaultAlbumBanner: todo默认banner格式为一张图片的地址https://lmg.jj20.com/up/allimg/1114/041621122252/210416122252-1-1200.jpg
  tencent-cos: # 腾讯云 COS
    platform: todo存储平台标识 # 存储平台标识
    enable-storage: true  # 启用存储
    secret-id: todo访问cos的secret-id
    secret-key: todo访问cos的secret-key
    region: todo存仓库所在地域 #存仓库所在地域
    bucket-name: todo储存桶名称
    domain: todo储存桶访问的域名 # 访问域名，注意“/”结尾，例如：https://abc.cos.ap-nanjing.myqcloud.com/
    base-path: love/ # 基础路径
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认1440分钟=一天）
  expireTime: 7
spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: true
  devtools:
    restart:
      enabled: true
  mail:
    host: smtp.qq.com
    password: todo邮件服务器密码
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    username: todo邮件服务器用户名
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.jokeo.pojo
springfox:
  documentation:
    swagger-ui:
      enabled: true

# 日志配置
logging:
  level:
    cn.jokeo.lovepig: debug
    org.springframework: warn